<?php

/**
 * @file
 * aiocalendar install/uninstall hooks
 */

/**
 * Implementation of hook_install().
 */
function aiocalendar_install() {

  $vocabulary = (object) array(
      'name' => t('Event Type'), 
      'description' => 'Event Categories for the AIO Calendar', 
      'machine_name' => 'event_type',
      'hierarchy' => 1,
      'module' => 'aiocalendar',
    );
  taxonomy_vocabulary_save($vocabulary);

}

